config/routes.rb
Rails.application.routes.draw do
  resources :comments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "products#index"
  get  "products/search"
  resources :products
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      if user.has_role? :admin
        # admin
        can :manage, :all
      elsif user.has_role? :modulator
        # modulator
        can [:read, :create, :update, :search], Product
        can [:read, :create, :update, :destroy], User, id: user.id
      elsif user.has_role? :anonymous
        # anonymous
        cannot :manage, :all
      else
        # none role
        can [:read, :create, :update, :search], Product, user_id: user.id
        can [:read, :create, :update, :destroy], User, id: user.id
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_create_commit { broadcast_prepend_to "comments" }
  after_update_commit { broadcast_replace_to "comments" }
  after_destroy_commit { broadcast_remove_to "comments" }
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :qty, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  belongs_to :user

  has_one_attached :main_image
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[ edit update destroy ]
  load_and_authorize_resource

  # GET /products or /products.json
  def index
    @products = Product.all.order(created_at: :desc)
  end
  
  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to root_path, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to root_path, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    if params[:name].present?
      @product_search = Product.where("lower(name) LIKE?", "%#{params[:name]}%").map{|h| h}
    else
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :qty, :main_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/comments/_comment.html.erb
<%= content_tag :tr, id: dom_id(comment) do %>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%= turbo_stream_from "comments" %>
    <%= turbo_frame_tag "comments" do %>
      <%= render @comments %>
    <% end %> 

    <%
=begin%>
 <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %> 
<%
=end%>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockHomework</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <%= turbo_include_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
    <nav class="navbar">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">Store</span>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"button-1 btn-logout" %>
      </div>
    </nav>
    <% end %>

    <div class="container"> 
        <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
  <%= form_with(model: product) do |form| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field input-group flex-nowrap mt-4">
      <span class="input-group-text" id="addon-wrapping"><%= form.label :name %></span>
      <%= form.text_field :name, class:"form-control", placeholder:"Name Product"%>
    </div>

    <div class="field input-group flex-nowrap mt-4 mb-4">
      <span class="input-group-text" id="addon-wrapping"><%= form.label :qty %> </span>
      <%= form.number_field :qty, class:"form-control", placeholder:"Quantity"%>
    </div>

    <%
=begin%>
 <div class="field input-group" >
      <%= form.file_field :main_image,  class:"form-control" ,placeholder:"Choose image"%>
    </div> 
<%
=end%>

    <div class="actions">
      <%= form.submit (), class:"button-1 button-sendfrom" %>
    </div>
  <% end %>

app/views/products/_modal.html.erb
 <!-- Modal -->
            <div class="modal fade" id=<%= "product#{product.id}" %> tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">warning</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <h2>Are you sure?</h2>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-danger"><%= link_to 'Delete', product, method: :delete, style:"color:white"%></button>
                  </div>
                </div>
              </div>
            </div>

app/views/products/_product.html.erb
<%= content_tag :tr, id: dom_id(product) do %>
  <td><%= product.name %></td>
  <td><%= product.qty %></td>

  <td><button class="button-1 button-edit"><%= link_to 'Edit', edit_product_path(product), style:"color:black" %></button></td>
  <td><button class="button-1 button-delete" data-bs-toggle="modal" data-bs-target=<%= "#product#{product.id}" %> >Delete</button></td>
  <%= render 'products/modal', product: product  %> 
<% end %>

app/views/products/edit.html.erb
<div class="form-container">
<h1>Editing Product</h1>

<%= render 'form', product: @product %>


<%= link_to 'Back', products_path, class:"button-1 button-back back-w" %>
</div>

app/views/products/index.html.erb
<div>
    <% if notice %>
    <div id="notice" class="alert alert-info" role="alert">
        <%= notice %>
    </div>
    <% end %>

      <div class="search">
        <h1 class="">Search</h1>
        <div class="input-group mb-3 search-form">
            <%= form_with url: "/products/search", method: :get do |form| %>
              <%= form.text_field :name, class:"form-control", placeholder:"Search name product" %>
              <%= form.submit "Search", class:"button-1 btn-search" %>
            <% end %>
        </div>
      </div>

    <div class="mt-5">
     <h1 class="mb-3">Products</h1>
      <button class="button-1 btn-newproduct"><%= link_to 'New Product', new_product_path, style:"color:white" %></button>


      <div class="tb-container">
      <table class="table table-borderless">
        <thead>
          <tr>
            <th>Name</th>
            <th>Qty</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
          <% if can? :read, product %>
            <tr>
              <td>
              <% if product.main_image.attached? %>
              <div class="main_image">
                <%= image_tag product.main_image, class:"rounded mx-auto d-block", height:70, width:70 %>
              </div>
              <% end %> 
              </td>
              <td><%= product.name %></td>
              <td><%= product.qty %></td>
              <% if can? :update, product %>
              <td><button class="button-1 button-edit"><%= link_to 'Edit', edit_product_path(product), style:"color:black" %></button></td>
              <% end %>
              <% if can? :destroy, product %>
              <td><button class="button-1 button-delete" data-bs-toggle="modal" data-bs-target=<%= "#product#{product.id}" %> >Delete</button></td>
              <% end %>
            </tr>
            <%= render 'modal', product: product  %> 
            <% end %>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  <br>

</div>

app/views/products/new.html.erb
<div class="form-container">
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class:"button-1 button-back back-w" %>
</div>

app/views/products/search.html.erb
<div style="height:100%">
    <%= link_to 'Back', products_path, class:"button-1 button-back"%>
    <% if @product_search %>
     <div>
        <table class="table table-borderless">
        <thead>
          <tr>
            <th>Name</th>
            <th>Qty</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @product_search.each do |product| %>
          <% if can? :read, product %>
            <tr>
              <td>
              <% if product.main_image.attached? %>
              <div class="main_image">
                <%= image_tag product.main_image, class:"rounded mx-auto d-block", height:70, width:70 %>
              </div>
              <% end %>
              </td>
              <td><%= product.name %></td>
              <td><%= product.qty %></td>
              <% if can? :update, product %>
              <td><button class="button-1 button-edit"><%= link_to 'Edit', edit_product_path(product), style:"color:black" %></button></td>
              <%end %>
              <% if can? :destroy, product %>
              <td><button class="button-1 button-delete" data-bs-toggle="modal" data-bs-target=<%= "#product#{product.id}" %> >Delete</button></td>
              <% end %>
            </tr>
            <%= render 'modal', product: product  %> 
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
    <% end %>
</div>